### ISSUE TITLE
When 'Quick Edit' option is used then the set price in other currency changes to the base currency exchanged price for the product.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/currency-per-product-for-woocommerce#13]
The set price is changing to the base currency exchange price when 'Quick Edit' option is used on the Products Page.

The issue is replicated only when 'Convert to shop default currency (including cart and checkout)' option is selected for Shop behaviour setting under the Currency per Product->Behaviour link.

Video: https://www.screencast.com/t/ptmesrmxboC

Forum: https://wordpress.org/support/topic/includes-x-tax-label-on-cart-checkout/

**Comment by nidhitatosaniya** [comment]
everything is working fine and no action is required. Hence I closing it.

**Comment by apeksha10** [comment]
I am re-opening this issue 

Please check the video: https://app.screencast.com/H3ERIoq96cMC5

Steps 
1. Currency per Product->Behaviour-->' Convert to shop default currency (including cart and checkout)'
2. Shop currency is Dollar, and product currency is set as Rupees 
3. Go to the product listing page, try to click on Quick Editior button, and check the value
4. Update the Product 
5. Again visit the same product and click on the Quick Editior button, the value is different.

**Comment by PratapDungrani** [comment]
@apeksha10 I have already fixed the issue here https://github.com/TycheSoftwares/currency-per-product-for-woocommerce/issues/55

Also, I tried to replicate the issue with the master copy but couldn't. Hence closing this one for now.
