### ISSUE TITLE
Does not work with WooCommerce Subscriptions plugin

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/currency-per-product-for-woocommerce#22]
The currency symbol does not display correctly when we manually add subscription and select the product. It displays the base currency of the product.

Link: https://wordpress.org/support/topic/woocommerce-subscriptions-24/#post-11936410

**Comment by nidhitatosaniya** [comment]
With latest copy it display correct currency symbol when we add manually subscriptions. Hence I closing it.
