### ISSUE TITLE
when 'Convert to currency of last product in cart' option is enabled then amount is not updated 

### ISSUE THREAD

**Issue by Dhara61** [TycheSoftwares/currency-per-product-for-woocommerce#40]
When 'Convert to currency of last product in cart' option is enabled then the amount is not updated. Currency symbol is updated fine. 

Steps: 

1. My default currency is USD and its value is 1 
2. Currency #1 [INR} and its value is 2 Screenshot: https://prnt.sc/uf14li 
3. Added a product with USD first and then added INR product https://prnt.sc/uf14d6 and then added INR https://prnt.sc/uf1426
4. So, all products should get converted to INR. This is working fine. Screenshot: https://prnt.sc/uf1426
5. But as you can see here the amount is not updating fine. The amount is the same as it was in USD, it should get double in value as they are getting converted in INR.

**Comment by Shasvat7** [comment]
This same behaviour will also happen when 'Convert to currency of first product in cart' option is enabled. So that also needs to be fix.
