### ISSUE TITLE
Product Currency symbol does not displayed when manually adding the order instead it shows the symbol of the default currency set.

### ISSUE THREAD

**Issue by Shasvat7** [TycheSoftwares/currency-per-product-for-woocommerce#47]
The currency symbol of the product is not getting displayed when we manually 'Add Order' from the backend. It is showing the default currency which is already set.

Suppose the particular product-currency is USD and the default currency set is INR. Then when we manually add the order from the backend it will show the default currency INR instead of the particular product-currency i.e.USD.
Product currency USD:- https://prnt.sc/10b7lh5
Adding order manually, product-currency coming INR: https://prnt.sc/10b7l6l

Ticket Link : https://tychesoftwares.freshdesk.com/a/tickets/25413

**Comment by ashokrane** [comment]
@apeksha10 Can you check if this above issue is same as #44 ?

**Comment by apeksha10** [comment]
Yes.. both issues are the same. 

Both issues mentioned incorrect currency symbol comes when we create manual order.
