### ISSUE TITLE
The currency symbol in the Mini cart is coming wrong even when the 'Fix mini cart' setting is enabled

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/currency-per-product-for-woocommerce#8]
The currency symbol in the Mini cart is coming wrong even when the 'Fix mini cart' setting is enabled in the Advanced tab.

Attaching screenshots of the settings: https://prnt.sc/ne5e10 , https://prnt.sc/ne5eb8 , https://prnt.sc/ne5kb4 , https://prnt.sc/ne5lp8 , https://prnt.sc/ne5idd

When I add a Dollar product to the cart, the mini cart shows the currency in Rupees.

Attaching a screenshot of the Mini cart: https://prnt.sc/ne5rti

**Comment by apeksha10** [comment]
The above same issue replicate on latest git copy.
The currency symbol in the Mini cart is coming wrong even when the 'Fix mini cart' setting is enabled.

screenshot of the settings : https://www.screencast.com/t/mElk6bV4dTE
https://www.screencast.com/t/8XwSTSn0
https://www.screencast.com/t/tANT4GDHnb9
https://www.screencast.com/t/pPdpvcKRAJDn
https://www.screencast.com/t/zo9KG5qe

https://www.screencast.com/t/cfeCjqas

hence re-open this issue

**Comment by ashokrane** [comment]
@apeksha10 Can you please test this issue with the copy before I committed the WPCS related changes?

**Comment by apeksha10** [comment]
I checked that issue before the most recent changes but same issue is replicated on that copy too

**Comment by Shasvat7** [comment]
This issue is not being replicated with latest copy of the plugin.And its working properly hence closing the issue.

**Comment by kenil802** [comment]
I have replicated this issue where the mini cart is not working. It is showing the wrong currency symbol. Hence I am re-opening this issue.

I see that the Cart and Checkout settings is kept to "Convert to the currency of the first product". But it should be "Convert to shop default currency". 

Suppose, the base currency is Turkish and the customer purchased the first product in Euro and the second product in Turkish. So, if we keep the setting to convert to currency first product, then it will show Euro symbol that is wrong. 

Instead, the option should be "convert to shop default currency" so whichever the product is selected, at the end it should be converted to the default currency.  

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/18481

**Comment by kenil802** [comment]
One more client faced this issue:

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/20202

**Comment by Sjors** [comment]
I'm seeing this issue now on my shop, despite running v1.4.8.

I noticed the pro version has a recent update v1.5.4 which mentions another(?) fix for this issue. Are you planning to add that to the free version too?
https://www.tychesoftwares.com/docs/docs/currency-per-product-for-woocommerce/changelog/
