### ISSUE TITLE
Getting the below error in the debug log.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/currency-per-product-for-woocommerce#82]
**Describe the bug**
Getting the below error in the debug log:

Output from Query monitor when currency per product plugin in enabled.

Function is_page was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. (This message was added in version 3.1.0.)
is_page()
wp-includes/query.php:588
is_cart()
wp-content/plugins/woocommerce/includes/wc-conditional-functions.php:98
Alg_WC_CPP_Core->is_cart_or_checkout()
wp-content/plugins/currency-per-product-for-woocommerce/includes/class-alg-wc-cpp-core.php:914
Alg_WC_CPP_Core->change_currency_code()
wp-content/plugins/currency-per-product-for-woocommerce/includes/class-alg-wc-cpp-core.php:950
apply_filters('woocommerce_currency')
wp-includes/plugin.php:205
get_woocommerce_currency()
wp-content/plugins/woocommerce/includes/wc-core-functions.php:465

**To Reproduce**
The client has reported this error to us. He has shared the screenshots of the setup. I tried to replicate this error at our end with the same settings but I am unable to replicate the same. 

**Expected behavior**
Such an error should not appear in the debug log file from our plugin.

**Screenshots**
https://app.screencast.com/frtQh2WKzkzuC
https://app.screencast.com/Z2ml8HgkOT8Ch
https://app.screencast.com/MAb2SwdtO4uoh
https://app.screencast.com/2IrVL8OE3Tbxz
https://app.screencast.com/kflRwsAxvbNCu

**Additional context**
https://support.tychesoftwares.com/conversation/636?folder_id=15

**Comment by mokshasharmila13** [comment]
I was unable to replicate the issue, so we asked for FTP access and checked the user's site. It turned out that they were using an old version of WooCommerce. We advised the user to update to the latest version and let us know if he still gets that error or not, but we have not received any response regarding the error.

**Comment by handelce** [comment]
@mokshasharmila13 What version of WooCommerce was the client using? Has that version been tested with the plugin or compatible with it?

**Comment by mokshasharmila13** [comment]
Our plugin has been tested with the client's WooCommerce 8.6.1 version and it is compatible.

**Comment by handelce** [comment]
@mokshasharmila13 There's a known issue with using the `is_page` function in WP. Please see https://gist.github.com/keiraarts/b9c0e635ac1364fd8464e0f4e332408a. It is good that we fix this if we find this issue in the plugin code. So, please check in the plugin code where ( or if ) we have used the `is_page` function and update the code based on the solution in the link I just shared.

**Comment by mokshasharmila13** [comment]
@handelce There is no need to implement the code as the is_page function is not present.
